### It will be include more advanced array manipulations and algorithms

In [1]:
import numpy as np

### A.1 ndarray Object Internals
Numpy ndarray -> Interpret a block of homogenously typed data as multidimensional array object.
dtype-> Determines how the dats is being interpreted (boolean,float,integer,string,etc)
ndarray internally consists on:
- pointer to data
- data type describing fixed-size value
- tuple indicating the arrays shape
- tuple of strides -> integer indicating the number of bytes to 'step' from one data to the next

In [2]:
np.ones((10,5)).shape
np.ones((10,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
o = np.ones((3,4,5))
o

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### NumPy Data Type Hierarchy
Checking if an array contains integers, floating-point number, string ot Python objects.


In [4]:
ints = np.ones(10,dtype = np.uint16)
floats = np.ones(10,dtype=np.float32)

print("Ints is float?" ,np.issubdtype(ints.dtype,np.floating))
print("Ints is int?",np.issubdtype(ints.dtype,np.integer))


Ints is float? False
Ints is int? True


In [5]:
# We can see all of the parent classes of a specific datatype by calling .mro()
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation
We may need to write some data algorithm for complicated cases of data manipulation in numpy

### Reshaping arrays

In [6]:
arr1 = np.array([4,6,3,56,3,6,47,9,4,4,65,12])
arr2 = arr1.reshape((3,4))

arr3 = arr2.reshape((2,6))
print(arr1)
print("")
print(arr2)
print("")
print(arr3)

[ 4  6  3 56  3  6 47  9  4  4 65 12]

[[ 4  6  3 56]
 [ 3  6 47  9]
 [ 4  4 65 12]]

[[ 4  6  3 56  3  6]
 [47  9  4  4 65 12]]


In [7]:
# One of the passed shape dimensions can be -1. In that case the value used for that dimension will be inferred from the data

arr4= np.arange(15).reshape((3,-1))
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr5 = np.arange(15).reshape(3,-1)
arr6 = arr5.ravel()
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr7 = np.array([1,4,5,3,6,8,7,9]).reshape(4,-1)
arr8 = arr7.ravel() 
arr8

array([1, 4, 5, 3, 6, 8, 7, 9])

In [10]:
#To always flatten we have flatten()
arr9 = arr7.flatten()
print(arr7,"\n")
print(arr8)
print(arr9)

[[1 4]
 [5 3]
 [6 8]
 [7 9]] 

[1 4 5 3 6 8 7 9]
[1 4 5 3 6 8 7 9]


### Concatenating and Splitting Arrays
numpy.concatenate takes a sequence (tuple,list,etc) of arrays and joins them in order along the input axis.


In [11]:
arr1 = np.array([[4,3,5],[6,8,9]])
arr2 = np.array([[5,8,9],[9,4,3]])
np.concatenate([arr1,arr2],axis=0)

array([[4, 3, 5],
       [6, 8, 9],
       [5, 8, 9],
       [9, 4, 3]])

In [12]:
np.concatenate([arr1,arr2],axis=1)

array([[4, 3, 5, 5, 8, 9],
       [6, 8, 9, 9, 4, 3]])

In [13]:
# Another way to concatenate. Concatenates as axis=0
np.vstack((arr1,arr2))

array([[4, 3, 5],
       [6, 8, 9],
       [5, 8, 9],
       [9, 4, 3]])

In [14]:
# Anothe way to concatenate. Concatenates as axis=1
np.hstack((arr1,arr2))


array([[4, 3, 5, 5, 8, 9],
       [6, 8, 9, 9, 4, 3]])

In [15]:
# Slices
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal((6,2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306],
       [ 2.34740965,  0.96849691]])

In [16]:
# We can split an array and the variables separated with comma will be the different values of the split
first,second,third,fourth= np.split(arr,[1,2,4],axis=0) #[1,3] -> Indicate the indices where it has to split
first

array([[-1.42382504,  1.26372846]])

### Stacking helpers: r_ and c_
Make stacking arrays more concise

In [17]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = rng.standard_normal((3,2))
np.r_[arr1,arr2] #Concatenates axis =0

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952],
       [ 0.78884434, -1.25666813]])

In [18]:
np.c_[arr1,arr2] #Concatenates axis = 1

array([[ 0.        ,  1.        , -0.75938718,  0.90219827],
       [ 2.        ,  3.        , -0.46695317, -0.06068952],
       [ 4.        ,  5.        ,  0.78884434, -1.25666813]])

In [19]:
np.c_[1:6,-10:-5]  #Concatenates in axis = 1
np.r_[1:6,-10:-5] #Concatenates in axis  =0

array([  1,   2,   3,   4,   5, -10,  -9,  -8,  -7,  -6])

# Repeating elements: Tile and repeat
Produce larger arrays
- repeat -> Replicates each element in an array somer number of times

In [20]:
arr = np.arange(4)
arr.repeat(2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [21]:
# Passing an array will do each element can be repeated a different number of times
arr.repeat([2,4,5,2])

array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3])

In [22]:
# Multidimensional arrays can have their elements repeated along a particular axis.
arr = rng.standard_normal((4,2))
arr

array([[ 0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852],
       [ 0.90291934, -1.62158273],
       [-0.15818926,  0.44948393]])

In [23]:
arr.repeat(2,axis=1) #If no axes passed, it wil flatten the array.

array([[ 0.57585751,  0.57585751,  1.39897899,  1.39897899],
       [ 1.32229806,  1.32229806, -0.29969852, -0.29969852],
       [ 0.90291934,  0.90291934, -1.62158273, -1.62158273],
       [-0.15818926, -0.15818926,  0.44948393,  0.44948393]])

In [24]:
# Tile -> stacking copies of an array along an axis.
arr
np.tile(arr,2) #It will repeat the value the time you put as parameter

array([[ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
       [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -0.15818926,  0.44948393]])

In [25]:
np.tile(arr,(2,2,2)) #It will repeat the value the time you put as parameter. Passing the tuple. Each position in the tuple represents the index and the value represents the times to repeat

array([[[ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
        [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
        [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
        [-0.15818926,  0.44948393, -0.15818926,  0.44948393],
        [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
        [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
        [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
        [-0.15818926,  0.44948393, -0.15818926,  0.44948393]],

       [[ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
        [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
        [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
        [-0.15818926,  0.44948393, -0.15818926,  0.44948393],
        [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
        [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
        [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
        [-0.15818926,  0.44948393, -0.15818926,  0.44948393]]])

In [26]:
np.tile(arr,(3,2))

array([[ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
       [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -0.15818926,  0.44948393],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
       [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -0.15818926,  0.44948393],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852,  1.32229806, -0.29969852],
       [ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -0.15818926,  0.44948393]])

### Fancy indexing Equivalents: take and put
Allows to get and set subsets or arrays

In [27]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [28]:
inds= [7,1,2,6]
inds

[7, 1, 2, 6]

In [29]:
arr[inds]

array([700, 100, 200, 600])

In [30]:
#We could use take to get the values of the given array in the position of the given array
arr.take(inds)

array([700, 100, 200, 600])

In [31]:
arr.put(inds,34) # Changes the values of the given values
arr

array([  0,  34,  34, 300, 400, 500,  34,  34, 800, 900])

In [32]:
arr.put(inds,[732,153,299,698]) # It changes the value according to the index
arr

array([  0, 153, 299, 300, 400, 500, 698, 732, 800, 900])

### Broadcasting
Governs how operation works between arrays of different shapes.
The simplest example occurs when combining a scalar value with an array.


In [33]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [34]:
arr * 4 # A scalar value 4 has been broadcast to all of the elements in the multiplication operation (array)

array([ 0,  4,  8, 12, 16])

In [67]:
arr = rng.standard_normal((4,3))
arr

array([[-1.99585661, -0.15524762,  1.06383087],
       [-0.27517157, -1.85333593, -0.12434193],
       [ 0.78497452,  0.2019986 , -0.42807444],
       [ 1.8482889 ,  1.89995289, -0.09842503]])

In [36]:
arr.mean(0) #We get the mean of axis 0.

array([0.21427922, 0.05955622, 0.1205802 ])

In [37]:
demeaned = arr - arr.mean(0) # (degaradar) # We substract the mean in axis 0 to each vlaue of the array.
demeaned

array([[-1.55788029, -0.14124381,  1.60415973],
       [ 2.40388021,  0.71780513,  0.708053  ],
       [-1.17326753, -1.2689445 , -1.53287221],
       [ 0.32726761,  0.69238318, -0.77934052]])

In [38]:
# Because we substract the mean, when we get the mean of the new value, it'll be 0
demeaned.mean(0)

array([2.77555756e-17, 0.00000000e+00, 5.55111512e-17])

### The broadcasting rule
Two arrays are compatible for broadcasting if for each trailing dimension (i.e starting from the end) the axis length match or if either of the lengths is 1. Broadcasting is then performed over the missing or length 1 dimensions

In [39]:
arr1 = np.arange(10).reshape((2,5))
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
arr2 = np.array([1,2]).reshape((2,1))
arr2

array([[1],
       [2]])

In [65]:
arr1 + arr2

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [69]:
arr

array([[-1.99585661, -0.15524762,  1.06383087],
       [-0.27517157, -1.85333593, -0.12434193],
       [ 0.78497452,  0.2019986 , -0.42807444],
       [ 1.8482889 ,  1.89995289, -0.09842503]])

In [70]:
arr.shape

(4, 3)

In [72]:
row_means = arr.mean(1)
row_means

array([-0.36242445, -0.75094981,  0.18629956,  1.21660558])

In [44]:
row_means.shape

(4,)

In [45]:
row_means.reshape((4,1)).shape

(4, 1)

In [74]:
demeaned = arr - row_means.reshape((4,1))
demeaned

array([[-1.63343216,  0.20717683,  1.42625533],
       [ 0.47577824, -1.10238612,  0.62660788],
       [ 0.59867496,  0.01569904, -0.614374  ],
       [ 0.63168331,  0.68334731, -1.31503062]])

In [47]:
demeaned.mean(1)

array([ 0.00000000e+00, -1.11022302e-16,  1.11022302e-16, -3.70074342e-17])

### Broadcasting over Other axes
Broadcasting with higher dimensional arrays can seem more mind-bending. You just have to follow the rules According to the broadcasting rule, the "broadcast dimensions" muts be 1 in the smaller array.
In case of three-dimensional case, broancasting over any three dimensions is only matter of reshaping the data to be shape compatible.
We have the need of adding a new axis with length 1 specifically for broadcasting purposes.
We can do it by reshape, but it is a tedious excercise.
Instead we use a special syntax tha NumPy offers for inserting a new axes by indexing
-> np.newaxis attribute along with full slices to insert the new axis

In [48]:
arr = np.zeros((4,4))
arr_3d = arr[:,np.newaxis,:]
arr_3d.shape

(4, 1, 4)

In [49]:
arr_1d = rng.standard_normal(3)
arr_1d

array([-1.22867499,  0.25755777,  0.31290292])

In [50]:
arr_1d[:,np.newaxis]

array([[-1.22867499],
       [ 0.25755777],
       [ 0.31290292]])

It's the same as:

In [51]:
arr_1d.reshape((3,1))

array([[-1.22867499],
       [ 0.25755777],
       [ 0.31290292]])

In [52]:
arr_1d[np.newaxis,:]

array([[-1.22867499,  0.25755777,  0.31290292]])

It's the same as:

In [53]:
arr_1d.reshape((1,3))

array([[-1.22867499,  0.25755777,  0.31290292]])

What if we had a three-dimensional array and wanted to demean axis 2. We would need to write:

In [54]:
arr = rng.standard_normal((3,4,5))
depth_means = arr.mean(2)
depth_means

array([[-0.02563128,  0.40974955,  0.23355791, -0.47375328],
       [-0.46815284, -0.42230756, -0.36024006,  0.130337  ],
       [-0.44986515,  0.37128039,  0.52640275, -0.39162408]])

In [55]:
depth_means.shape

(3, 4)

In [75]:
demeaned = arr - depth_means[:,:,np.newaxis]

In [57]:
demeaned.mean(2)

array([[ 4.44089210e-17,  0.00000000e+00, -4.44089210e-17,
        -1.11022302e-17],
       [-1.11022302e-17, -1.11022302e-17,  0.00000000e+00,
         4.44089210e-17],
       [-2.22044605e-17,  4.44089210e-17, -4.44089210e-17,
        -4.99600361e-17]])

In [58]:
demeaned

array([[[-0.10518041,  1.2956144 , -0.06733118, -0.04051961,
         -1.08258319],
        [-0.2737927 ,  0.93732821, -0.34860553, -0.33883495,
          0.02390498],
        [ 0.04392575,  0.29669447,  0.30316305,  0.3847921 ,
         -1.02857537],
        [ 0.77378423, -1.12894831,  0.74055211, -0.7878705 ,
          0.40248247]],

       [[ 0.94220257,  0.05329908,  0.56586934, -1.172265  ,
         -0.38910599],
        [ 1.11058935, -0.73222202,  1.07275995, -0.96605239,
         -0.48507489],
        [-0.73518525,  0.36738575,  0.89459996, -0.70556779,
          0.17876732],
        [ 1.4916148 , -0.44772894, -0.94615196,  0.25624202,
         -0.35397592]],

       [[-0.25182566, -1.34584803,  1.26819077, -0.12116775,
          0.45065067],
        [-1.43492311,  0.93043411,  0.37659255,  0.60959552,
         -0.48169908],
        [-0.05848422,  0.3642044 ,  0.49660662, -0.21401936,
         -0.58830744],
        [ 0.03214444, -0.3570199 , -0.57385482,  0.75165874,
          0

### Setting array values by broadcasting
The same rule applies to setting values via array indexing.


In [85]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
arr[:] = 5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [87]:
col = np.array([1.45, 0.5, -0.65, 5-41])

In [111]:
arr[:] = col[np.newaxis,:]
arr

array([[  1.45,   0.5 ,  -0.65, -36.  ],
       [  1.45,   0.5 ,  -0.65, -36.  ],
       [  1.45,   0.5 ,  -0.65, -36.  ]])

In [112]:
arr[2:] = [1.5]
arr

array([[  1.45,   0.5 ,  -0.65, -36.  ],
       [  1.45,   0.5 ,  -0.65, -36.  ],
       [  1.5 ,   1.5 ,   1.5 ,   1.5 ]])

## Advanced ufunc Usage
There are additional features that can help to write more concise code without explicit loops

### ufunc Instance Methods
Each of NumPy's binary ufuncs has special methods for performing special vectorized operations.


In [117]:
# reduce -> takes a singe array and aggregates its values, optionally along an axis
arr = np.arange(7)
np.add.reduce(arr)

21

In [118]:
arr.sum()

21

In [119]:
# You can pass the axis where you want to perform the reduction. 
# np.logical_and -> Allows to see whether the values in each row of an array are sorted
my_rng = np.random.default_rng(12346)
arr = my_rng.standard_normal((5,5))
arr

array([[-0.903889  ,  0.15713146,  0.89761199, -0.76219554, -0.17625556],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-0.87971984, -1.69847913, -1.81891091,  0.11895453, -0.44409513],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [ 1.04984775,  1.02967072, -0.42005533,  0.78626627,  0.96124929]])

In [124]:
arr[::2].sort(1)

In [121]:
arr[:,:-1] < arr [:,1:]

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [122]:
np.logical_and.reduce(arr[:,:-1] < arr[:,1:],axis =1)

array([ True, False,  True, False,  True])

In [128]:
# accumulate ufun -> Related to reduce. Produces an array of the same size with the intermediate "accumulated" values
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
np.add.accumulate(arr,axis=1) #It like a acumsum.

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [141]:
arr = np.arange(4).repeat([1,2,2,1])
arr

array([0, 1, 1, 2, 2, 3])

In [146]:
#multiply.outer
mult_arr = np.multiply.outer(arr,np.arange(10))
mult_arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [147]:
mult_arr.shape

(6, 10)

In [159]:
# reduceat -> Performs a local reduce. Does a group by operation in which slice of the array are aggregated together. It accepts a sequence of "bin edges" that indicate hot to split and aggregate the values
arr = np.arange(10) 
np.add.reduceat(arr,[0,1,3])


array([ 0,  3, 42])

In [162]:
arr = np.multiply.outer(np.arange(4),np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [179]:
np.add.reduceat(arr,[0,2,4],axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### Structured and record arrays
Up until now, ndarray is a homogeneous data container. It's a block of memory in which each element takes up the same number of bytes, determined by the data type. 
A structured array is an ndarray in which each element can be thought of as representing a struct in C

In [180]:
dtype = [('x',np.float64),('y',np.int32)]
dtype

[('x', numpy.float64), ('y', numpy.int32)]

In [182]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

### Nested Data Types and Multidimensional Fields
When specifying a structured data type, you can additionally pass a shape (as an int or tuple)


In [183]:
dtype = [('x', np.int64,3),('y',np.int32)]
arr = np.zeros(4,dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])