### It will be include more advanced array manipulations and algorithms

In [1]:
import numpy as np

### A.1 ndarray Object Internals
Numpy ndarray -> Interpret a block of homogenously typed data as multidimensional array object.
dtype-> Determines how the dats is being interpreted (boolean,float,integer,string,etc)
ndarray internally consists on:
- pointer to data
- data type describing fixed-size value
- tuple indicating the arrays shape
- tuple of strides -> integer indicating the number of bytes to 'step' from one data to the next

In [7]:
np.ones((10,5)).shape

(10, 5)

In [10]:
o = np.ones((3,4,5))
o

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### NumPy Data Type Hierarchy
Checking if an array contains integers, floating-point number, string ot Python objects.


In [17]:
ints = np.ones(10,dtype = np.uint16)
floats = np.ones(10,dtype=np.float32)

print("Ints is float?" ,np.issubdtype(ints.dtype,np.floating))
print("Ints is int?",np.issubdtype(ints.dtype,np.integer))

Ints is float? False
Ints is int? True


In [25]:
# We can see all of the parent classes of a specific datatype by calling .mro()
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation
We may need to write some data algorithm for complicated cases of data manipulation in numpy

### Reshaping arrays

In [35]:
arr1 = np.array([4,6,3,56,3,6,47,9,4,4,65,12])
arr2 = arr1.reshape((3,4))

arr3 = arr2.reshape((2,6))
print(arr1)
print("")
print(arr2)
print("")
print(arr3)

[ 4  6  3 56  3  6 47  9  4  4 65 12]

[[ 4  6  3 56]
 [ 3  6 47  9]
 [ 4  4 65 12]]

[[ 4  6  3 56  3  6]
 [47  9  4  4 65 12]]


In [39]:
# One of the passed shape domensionx can be -1. In that case the value used for that dimension will be inferred from the data

arr4= np.arange(15).reshape((5,-1))
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
arr5 = np.arange(15).reshape(3,-1)
arr6 = arr5.ravel()
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr7 = np.array([1,4,5,3,6,8,7,9]).reshape(4,-1)
arr8 = arr7.ravel() 
arr8


array([1, 4, 5, 3, 6, 8, 7, 9])

In [60]:
#To always flatten we have flatten()
arr9 = arr7.flatten()
print(arr7)
print(arr8)
print(arr9)

[[1 4]
 [5 3]
 [6 8]
 [7 9]]
[1 4 5 3 6 8 7 9]
[1 4 5 3 6 8 7 9]


### Concatenating and Splitting Arrays
numpy.concatenate takes a sequence (tuple,list,etc) of arrays and joins them in order along the input axis.


In [88]:
arr1 = np.array([[4,3,5],[6,8,9]])
arr2 = np.array([[5,8,9],[9,4,3]])
np.concatenate([arr1,arr2],axis=0)

array([[4, 3, 5],
       [6, 8, 9],
       [5, 8, 9],
       [9, 4, 3]])

In [89]:
np.concatenate([arr1,arr2],axis=1)

array([[4, 3, 5, 5, 8, 9],
       [6, 8, 9, 9, 4, 3]])

In [90]:
# Another way to concatenate 
np.vstack((arr1,arr2))

array([[4, 3, 5],
       [6, 8, 9],
       [5, 8, 9],
       [9, 4, 3]])

In [91]:
np.hstack((arr1,arr2))

array([[4, 3, 5, 5, 8, 9],
       [6, 8, 9, 9, 4, 3]])

In [97]:
# Slices
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal((6,2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306],
       [ 2.34740965,  0.96849691]])

In [109]:
first,second,third, fourth= np.split(arr,[1,2,4]) #[1,3] -> Indicate the indices where it has to split
fourth

array([[ 0.36105811, -1.95286306],
       [ 2.34740965,  0.96849691]])

### Stacking helpers: r_ and c_
Make stacking arrays more concise

In [119]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = rng.standard_normal((3,2))
np.r_[arr1,arr2] #Concatenates rows

array([[0.        , 1.        ],
       [2.        , 3.        ],
       [4.        , 5.        ],
       [0.06114402, 0.0709146 ],
       [0.43365454, 0.27748366],
       [0.53025239, 0.53672097]])

In [120]:
np.c_[arr1,arr2] #Concatenates columns

array([[0.        , 1.        , 0.06114402, 0.0709146 ],
       [2.        , 3.        , 0.43365454, 0.27748366],
       [4.        , 5.        , 0.53025239, 0.53672097]])

In [126]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

# Repeating elements: Tile and repeat
Produce larger arrays
- repeat -> Replicates each element in an array somer number of times

In [127]:
arr = np.arange(4)
arr.repeat(2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [129]:
# Passing an array will do each element can be repeated a different number of times
arr.repeat([2,4,5,2])

array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3])

In [134]:
# Multidimensional arrays can have their elements repeated along a particular axis.
arr = rng.standard_normal((4,2))

In [135]:
arr

array([[ 0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995],
       [-0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ]])

In [139]:
arr.repeat(2,axis=1) #If no axes passed, it wil flatten the array


array([ 0.68828179,  0.68828179, -1.15452958, -1.15452958,  0.65045239,
        0.65045239, -1.38835995, -1.38835995, -0.90738246, -0.90738246,
       -1.09542531, -1.09542531,  0.00714569,  0.00714569,  0.5343599 ,
        0.5343599 ])

In [147]:
# Tile -> stacking copies of an array along an axis.
arr
np.tile(arr,2)

array([[ 0.68828179, -1.15452958,  0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995,  0.65045239, -1.38835995],
       [-0.90738246, -1.09542531, -0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ,  0.00714569,  0.5343599 ]])

In [142]:
arr

array([[ 0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995],
       [-0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ]])

In [151]:
np.tile(arr,(3,2))

array([[ 0.68828179, -1.15452958,  0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995,  0.65045239, -1.38835995],
       [-0.90738246, -1.09542531, -0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ,  0.00714569,  0.5343599 ],
       [ 0.68828179, -1.15452958,  0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995,  0.65045239, -1.38835995],
       [-0.90738246, -1.09542531, -0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ,  0.00714569,  0.5343599 ],
       [ 0.68828179, -1.15452958,  0.68828179, -1.15452958],
       [ 0.65045239, -1.38835995,  0.65045239, -1.38835995],
       [-0.90738246, -1.09542531, -0.90738246, -1.09542531],
       [ 0.00714569,  0.5343599 ,  0.00714569,  0.5343599 ]])

### Fancy indexing Equivalents: take and put
Allows to get and set subsets or arrays

In [152]:
arr = np.arange(10) * 100

In [154]:
inds= [7,1,2,6]

In [155]:
arr[inds]

array([700, 100, 200, 600])

In [156]:
#We could use take
arr.take(inds)

array([700, 100, 200, 600])

In [159]:
arr.put(inds,34) # Changes the values of the given values
arr

array([  0,  34,  34, 300, 400, 500,  34,  34, 800, 900])

In [167]:
arr.put(inds,[732,153,299,698]) # It changes the value according to the index
arr

array([  0, 153, 299, 300, 400, 500, 698, 732, 800, 900])